### ISSUE TITLE
FriendlyName/childofType is fragile, maybe use circuitFunction instead

### ISSUE THREAD

**Issue by rflemming** [bsileo/SmartThings_Pentair#6] opened 2017-12-03 17:36 UTC
Both the light and pool switches that are part of the controller fail on my system.  The light I think I understand in that the friendlyName of pool light is "POOL LIGHT" and not "LIGHTS" as hardcoded in the app:

"4":{"number":4,"numberStr":"circuit4","name":"POOL LIGHT","circuitFunction":"Light","status":0,"freeze":0,"macro":0,"delay":0,"light":{"group":-1,"colorStr":"off","color":-1},"friendlyName":"POOL LIGHT"}

The pool pump I don't quite understand though since that seems correct with the friendlyName being "POOL":

"6":{"number":6,"numberStr":"circuit6","name":"POOL","circuitFunction":"Pool","status":1,"freeze":1,"macro":0,"delay":0,"light":{"group":-1,"colorStr":"off","color":-1},"friendlyName":"POOL"}

Attempting to use either of these results in an error:

17:01:42.438 ERROR Asking to queue malformed packet: 255,0,255,165,0,16,33,134,2,NaN,1,0,0
TypeError: Cannot read property 'name' of undefined
    at Object.setCircuit (/home/pi/nodejs-poolController-master/src/lib/equipment/circuit.js:464:75)
    at /home/pi/nodejs-poolController-master/src/lib/comms/server.js:215:31
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/nodejs-poolController-master/node_modules/express/lib/router/index.js:281:22
    at param (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/index.js:354:14)
    at param (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/index.js:365:14)
    at param (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/index.js:410:3)
    at next (/home/pi/nodejs-poolController-master/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/pi/nodejs-poolController-master/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/home/pi/nodejs-poolController-master/node_modules/send/index.js:270:17)

circuitFunction might be a better value to look at rather than friendlyName since it can't contain arbitrary strings.  At a minimum some error handling around not being able to find a matching circuit ID is probably in order.  I think these switches are actually somewhat redundant to the functionality provided by the circuit switches anyway.  I'd rather the pool pump button be replaced with a tile showing the pool's current run mode:  Auto, Service, Timeout, Heat, Freeze, but I don't think that's available at the moment from the API.

**Comment by rflemming** [comment] 2017-12-04 04:40
Alternatively if you really did want to keep the pool and spa pump switches with the pool and spa tiles you could just omit those circuits from the block of circuit tiles.  That assumes that circuits 1 and 6 are always the spa and pool (I think they are) in which case the circuitFunction logic isn't really necessary at all.

**Comment by bsileo** [comment] 2017-12-07 02:52
Thanks for the feedback on circuitFunction - I am working on moving the code over to that model. I am torn on the pool and spa switch. The problem is that you can not have a dynamic UI in SmartThings. In this case, since I do not know which circuits are those functions, I can not easily remove them from the block of 8 at the bottom. One approach is to make all of the circuit control switches more generic and build the association to what they do in software. mapping them over. I am going to work on some labeling of them next per #3 and then from there think about more refactoring for the UI.

**Comment by bsileo** [comment] 2017-12-07 03:07
Looking at my system, I see the following for Circuit 2 for the Pool lights. I am thinking Intellibrite is not a generic way to determine this is the light circuit since not all systems will have this type of lights?  Thought son how to handle this? Maybe "name" is the better option. For that I have:

name:"SPA"
name:"POOL"
"name": "LIGHTS"

`2": {
"number": 2,
"numberStr": "circuit2",
"name": "LIGHTS",
"circuitFunction": "Intellibrite",
"status": 1,
"freeze": 0,
"macro": 0,
"delay": 0,
"light": {
"group": 1,
"colorStr": "off",
"color": -1
},
"friendlyName": "LIGHTS"
},

**Comment by rflemming** [comment] 2017-12-07 18:54
There is a static list of valid circuit functions:

https://github.com/tagyoureit/nodejs-poolController/blob/master/src/etc/constants.js#L326

so you could check if the circuit is one of; Light, Intellibrite and I guess SAM Light and SAL Light.  The problem is what if you have more than one light. So I had a different thought regarding lights.  If you still want to have a generic light button then perhaps it should mimic the "All On" function on the controller.  I don't think the API has an "All On" command, but you don't actually need it either.  You could just iterate over each circuit and send the on/off command for each circuit with a light function.  There's a catch though if you read the manual:
 
https://www.pentairpool.com/~/media/websites/pool/downloads/automation/manuals/intellitouch_pool_and_spa_control_system_users_guide_english.pdf

There is a Sync function that makes sure all the color changing lights are in sync with each other.  The API doesn't support that so simply turning all of the lights on would probably be screwy if you had multiple color changing lights (I don't).  So in retrospect adding "All On", "All Off", and "Sync" functions to the API might be necessary to pull this off.  I'd honestly just leave out the light button on the controller tile.

I'm pretty sure that the spa and pool pumps are always on circuits 1 and 6 so if you want to have on/off  for those on the pool/spa tiles just remove those circuits from the circuits tiles as to not be redundant.

**Comment by bsileo** [comment] 2017-12-14 05:04
Completed updates to harden this approach and also dropped 1 and 6 form the generic set to simply the UI a bit. Still work to be done on the light circuit in terms of whether to map that or may just remove this and allow the correct generic to be set to the light function.  Will open a new issue for this aspect and close this one.

**Closed by bsileo** 2017-12-14 05:04 UTC
