### ISSUE TITLE
Pool Controller device screen blank

### ISSUE THREAD

**Issue by johnny2678** [bsileo/SmartThings_Pentair#1] opened 2017-11-30 21:30 UTC
Continuing from the Pool Controller Issue... [https://github.com/tagyoureit/nodejs-poolController/issues/64](https://github.com/tagyoureit/nodejs-poolController/issues/64)

Progress... sort of... no more errors in the ST logs but the device screen is still blank:
![image](https://user-images.githubusercontent.com/8219743/33455808-40c23892-d5eb-11e7-9ad8-05f967d26290.png)

and what should I do about the 8+ (Aux 1) devices that it created? Can I delete them?
![image](https://user-images.githubusercontent.com/8219743/33455874-6849817c-d5eb-11e7-8087-f49d4e1f336c.png)

```
cc5dff39-606a-4111-ac14-22196e0bcd31  4:19:22 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  4:13:18 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  4:07:24 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  4:01:34 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  4:01:34 PM: info Requested a refresh
cc5dff39-606a-4111-ac14-22196e0bcd31  4:01:23 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  3:49:23 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  3:43:24 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  3:37:23 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  3:31:34 PM: debug Executing 'sendEthernet' http://192.168.5.31:3000/all
cc5dff39-606a-4111-ac14-22196e0bcd31  3:31:34 PM: info Requested a refresh
cc5dff39-606a-4111-ac14-22196e0bcd31  3:30:36 PM: debug Device Network Id set to B827EBB17EB3
cc5dff39-606a-4111-ac14-22196e0bcd31  3:30:36 PM: trace updated(): Ran within last 5 seconds so aborting.
cc5dff39-606a-4111-ac14-22196e0bcd31  3:30:33 PM: trace updated(): Ran within last 5 seconds so aborting.
```

**Comment by donkarnag** [comment] 2017-11-30 21:43
Same result here.  Although my default layout is a bit different - see attached.  
![img_c8da35347985-1](https://user-images.githubusercontent.com/20792363/33456466-63a49eac-d5d4-11e7-9436-1334944945d4.jpeg)

**Comment by donkarnag** [comment] 2017-11-30 21:51
Interesting note - Double checking everything I noticed that I had edited, but not published, the Temperature Measurement Capability device type.  My screen now looks like @johnny2678 's and Aux2 - Aux8, Temperature Solar, Pool and Spa showed up.  Still nothing populating though.

**Comment by donkarnag** [comment] 2017-11-30 22:19
@bsileo I uncommented some of your debug lines in the `parse` function, and noticed that it is looking for   log.debug "msg.headers['x-event']", which does not show up in the headers - and that line seems to quietly error out.  I think I remember a conversation about making that change in @tagyoureit 's code.  Did that get changed somewhere else?

**Comment by donkarnag** [comment] 2017-11-30 22:23
```
2:21:35 PM: debug HEADERS: [content-length:8554, http/1.1 200 ok:null, x-powered-by:Express, connection:keep-alive, content-type:application/json; charset=utf-8, date:Thu, 30 Nov 2017 22:21:34 GMT, etag:W/"216a-/AI3QaNY0rQDz/CbhRAbBX4CGmE"]
```

**Comment by donkarnag** [comment] 2017-11-30 22:31
yup, that's part of it.  x-events is returning 'null'.  I pulled the parseCircuits and parseTemps outside of the 'case' and they are starting to process.  But still not populating...

**Comment by bsileo** [comment] 2017-11-30 22:52
The x-event HEader should be populated by the outputToSmarthings.js code. This is in the notify function within that code. Is it possible you have a different version of that js installed in your environment? I updated the orignal code with this UI to add that header.

**Comment by donkarnag** [comment] 2017-11-30 22:52
```
    parseTemps(msg.json.temperature)
    parseCircuits(msg.json.circuit)
```
the last bits of each should be singular...

**Comment by donkarnag** [comment] 2017-11-30 22:53
let me check

**Comment by bsileo** [comment] 2017-11-30 22:55
[Aside] The All socket / event does not fire from a Refresh at this stage. This is a problem within Smarthings and PoolController.  You can not really do an interactive call from ST to a LAN device without adding more overhead via a separate Smartapp and going to the cloud. But it works out Ok as anytime something changes the Pool Controller broadcasts this on the RS-485 bus which then updates ST via Socket.io.  There is the occasion when it gets out of sync for me so far especially with a circuit, but as soon as any circuit updates it will refresh all of them.

**Comment by donkarnag** [comment] 2017-11-30 22:58
I was just thinking the same thing - the refresh calls ip:3000/all, which does not send the right headers back.  As I was playing with it, we may be able to just call parseWhatever(), which will quietly fail if it can't find the right part of the response.

**Comment by bsileo** [comment] 2017-11-30 23:00
The problem is actually that the parse never gets called for this case. As far as I can tell the ST platform does not allow the results of this HubAction to go to parse.  What wee are seeing in Parse are the results of HTTP calls coming in from the poolController to the Hub with a Notify verb. 

What I am thinking is to check on a separate REST call which will force an All update on the socket.io side. Lame..but may be the best approach with the ST limitations.

**Comment by donkarnag** [comment] 2017-11-30 23:08
This seems to be working for me on a refresh from the ST app:
```
def parse(String description) {  
  //log.debug "Executing parse()"
  def msg = parseLanMessage(description)
  //log.debug "Full msg: ${msg}"
  //log.debug "HEADERS: ${msg.headers}"
  //log.debug "JSON: ${msg.json}"
  //log.debug "x-event: ${msg.headers['x-event']}"
  log.debug "msg.JSON.Circuits: ${msg.json.circuit}"
  log.debug "msg.JSON.Time: ${msg.json.time}"
  log.debug "msg.JSON.Temp: ${msg.json.temp}"
  log.debug "msg.JSON.Pump: ${msg.json.pump}"
    parseTemps(msg.json.temp)
    parseCircuits(msg.json.circuit)
	parseTime(msg.time)
/*
  switch (msg.headers['x-event']) {
    case 'circuit':
        parseCircuits(msg.json)
        break
    case 'all':
      	parseTemps(msg.json.temperature)
    	parseCircuits(msg.json.circuit)
        break
    case 'temp':
    	parseTemps(msg.json)      
        break
    case 'chlorinator':
    	parseChlorinator(msg.json)
        break
  }
  */
}
```

**Comment by donkarnag** [comment] 2017-11-30 23:09
...well, still a WIP, but circuits are updating, and it trying hard on the rest...

**Comment by bsileo** [comment] 2017-11-30 23:19
Not sure why you are not getting the x-event header. You should see the calls sending you Smarthings results in the Poolcontroller bootstrap. And looking at that code on the node side I see no way it is not setting that header. 

![log](https://user-images.githubusercontent.com/6116016/33460147-dfcf0208-d5fa-11e7-90ef-f197fa8938bb.png)

from outputToSmarthings.js:

```    var opts = {
            method: 'NOTIFY',
            host: address,
            port: port,
            path: '/notify',
            headers: {
              'CONTENT-TYPE': 'application/json',
              'CONTENT-LENGTH': Buffer.byteLength(json),
              'X-EVENT': event,
            }
          };

**Comment by donkarnag** [comment] 2017-11-30 23:35
sorry if I am behind on this, but it would help if i could catch up.
On refresh, ST calls IP:3000/all, which is not connected to outputToSmartthings, right?
Whatever is outputting /all needs to pass x-event, and then parse would work as written.
Right?

**Comment by bsileo** [comment] 2017-11-30 23:45
@donkarnag  The ST call to /all actually does not do anything with respect to updating what you see in the ST App. This is what is broken and I prob should remove the Refresh button until it is fixed. 

Temps get updated often because the bus gets those all the time.
Circuits and Chlorinator only get updated when something changes. So to refresh ALL of them, update any single one.

If you watch the Bootstrap debug UI (or look at the log on poolcontroller, wherever you have it set to go) you can see the Smartthings updates get triggered there and see those same events show up in the ST logs.

**Comment by donkarnag** [comment] 2017-11-30 23:56
@bsileo I think it was broken because the switch function couldn't find x-event, and needed some term updates due to tag's changes.  This works, however, and I can see the successful output in ST Live Logging.  As an aside, I don't think the push from the pool Controller is working, at least ST is not logging anything at all except for my refreshes, so I am pretty sure this is all due to the refresh code.  

```
def parse(String description) {  
  //log.debug "Executing parse()"
  def msg = parseLanMessage(description)
  //log.debug "Full msg: ${msg}"
  //log.debug "HEADERS: ${msg.headers}"
  //log.debug "JSON: ${msg.json}"
  //log.debug "x-event: ${msg.headers['x-event']}"
  //log.debug "msg.JSON.Circuits: ${msg.json.circuit}"
  //log.debug "msg.JSON.Time: ${msg.json.time}"
  //log.debug "msg.JSON.Temp: ${msg.json.temperature}"
  //log.debug "msg.JSON.Pump: ${msg.json.pump}"
  if (msg.json.temperature != null) {parseTemps(msg.json.temperature)} else {log.debug("no Temps in msg")}
  if (msg.json.circuit != null){ parseCircuits(msg.json.circuit)} else {log.debug("no Circuits in msg")}
  if (msg.json.time != null) {parseTime(msg.json.time)} else {log.debug("no Time in msg")}
  if (msg.json.pump != null) {parsePump(msg.json.pump)} else {log.debug("no Pumps in msg")}
  if (msg.json.schedule != null) {parseSchedule(msg.json.schedule)} else {log.debug("no Schedule in msg")}
  if (msg.json.valve != null) {parseValve(msg.json.valve)} else {log.debug("no Valve in msg")}
  if (msg.json.chlorinator != null) {parseChlorinator(msg.json.chlorinator)} else {log.debug("no Chlor in msg")}
  if (msg.json.intellichem != null) {parseIntellichem(msg.json.intellichem)} else {log.debug("no Chem in msg")}
}

def parseTime(msg) {
	log.info("Parse Time: ${msg}")
}
def parsePump(msg) {
	log.info("Parse Schedule: ${msg}")
}
def parseSchedule(msg) {
	log.info("Parse Schedule: ${msg}")
}
def parseValve(msg) {
	log.info("Parse Valve: ${msg}")
}
def parseIntellichem(msg) {
	log.info("Parse Intellichem: ${msg}")
}
```

**Comment by donkarnag** [comment] 2017-11-30 23:58
I get ST logs like this (ST is horrible at logging, no? I get like half of the logs...)
```
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:56:59 PM: debug Child==Controller Pool (Aux 2) --> 0
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:56:59 PM: debug Child==Controller Pool (Aux 3) --> 0
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:57:00 PM: debug Child==Controller Pool (Aux 4) --> 0
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:57:00 PM: debug Child==Controller Pool (Aux 5) --> 0
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:57:00 PM: debug Child==Controller Pool (Aux 7) --> 0
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:57:00 PM: debug Child==Controller Pool (Aux 6) --> 1
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:56:59 PM: info Parse Circuits
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:56:58 PM: info Parse Temps
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:56:57 PM: debug Executing 'sendEthernet' http://IP:3000/all
2fdfdefc-f265-43ed-996c-fba4fc52edbd  3:56:57 PM: info Requested a refresh
```

**Comment by bsileo** [comment] 2017-12-01 00:32
One issue here may be the version of poolcontroller you are running with @donkarnag . I bumped up to the latest 4.x-Dev code recently and made things compatible with that. I did not do a good job looking at backwards compatible with the changes made there and I suspect this why the tags are not matching for you. This is tied to [issue #56](https://github.com/tagyoureit/nodejs-poolController/issues/57) over there.

**Comment by bsileo** [comment] 2017-12-01 00:34
I am not sure about the Socket updates not coming but my guess is this is related to setup of your App. Double check the Device Network ID for your pool controller? That is all hacked together in my code right now. It needs to be the MAC address of the poolcontroller device, all caps, no colons.

![image](https://user-images.githubusercontent.com/6116016/33462419-792df274-d605-11e7-97ff-1ed7a771ab38.png)

**Comment by donkarnag** [comment] 2017-12-01 00:35
ok - working both ways now.  I manually edited your stuff in and spelled it smartthings, while you spelled it smartThings - apparently that matters.  This does seem to cause some very verbose logging, but at the least the circuits are updating as expected - and of course very rapidly.  If you want to throttle some of the outputs down a bit, I added this to another integration:
```
    var uploadTimePump = 0;//new Date().getTime();  //0 allows it to fire on startup; the other requires it to wait a minute to keep from overloading the target

    socket.on('pump', function(data) {
      var newTime = new Date().getTime();
      container.logger.info('UploadTime Pump: '+uploadTimePump);
      container.logger.info('Difference in Upload Time'+(newTime - uploadTimePump));
      container.logger.info('pump data to upload: '+JSON.stringify(data));
     if ((newTime - uploadTimePump) > 500) {
        container.logger.debug((newTime - uploadTimePump)+'millis - Uploading *Pump*');
        uploadTimePump = newTime;
        notify('pump', data);
      } else {
        container.logger.info('Pump socket - too soon');
      }
    })
```

**Comment by bsileo** [comment] 2017-12-01 00:35
And if you figure out why refresh works for you, I am interested. I definitely never see parse() called when I run the refresh call.

**Comment by donkarnag** [comment] 2017-12-01 00:54
PS @bsileo , I love it.  Tomorrow I will try to extend this into the intellichem, which I think I can do based on your chlorinator.  It may be handy to have a setting that adds/remove sections of the screen for Chlorinator and/or Intellichem so you won't see things that don't matter (maybe that would be good for the circuits too - I only use 3 of the 8.  

And maybe I can take a look at the light function - I see it in code but nothing shows up.

But, I am very excited - this is so much more handy than both the Pentair remote and the ScreenLogic2 app.

**Comment by donkarnag** [comment] 2017-12-01 02:04
@bsileo give the code I pasted above a try.  I found that the refresh was failing for two reasons - 
1. x-event wasn't found in the headers of the data pull so the switch function wasn't working, and
2. temperature and circuit in the below needed to be singular, per @tagyoureit 's recent edits.
```
      	parseTemps(msg.json.temperatures)
    	parseCircuits(msg.json.circuits)
```
By removing the switch and changing those terms, it works for me, as long as ip:3000/all returns something.

**Comment by tagyoureit** [comment] 2017-12-01 06:01
You guys are making me want to spend the $50 to get a hub and start playing with it.  Being that I have Siri and Alexa already on that list makes it a hard sell!  Do any of you use Alexa with Smartthings?  I'm pretty sure I could write a direct Alexa plugin so wondering why I might want Smartthings in the mix...

**Comment by bsileo** [comment] 2017-12-01 13:45
I have been on SmartThings going way back to the Kickstarter days @tagyoureit so I am a bit committed.  Generally speaking I always feel annoyed working on that platform...too many little annoying things - crappy dev environment, questionable apps, odd issues with automations not firing, etc.  I have a bunch of z-wave devices I am slowly replacing that also keep me tied there.  Z-wave is a whole other issue that I would definitely avoid in this day and age - wifi or zigbee are much better options. There certainly is a vibrant community of devs around ST which means lots of apps and devices to work with...just that most of it also turns in to lots of work!

**Comment by bsileo** [comment] 2017-12-01 14:27
@donkarnag Thanks for the code. That is working well for me now - I guess I totally missed that these were coming through probably due to the lame logging / lack of decent dev environment in ST and me not seeing the debug code.  I think we are still on different versions of poolController as I get plurals back not singular, but I am just coding for both for now.

FYI I opened a separate issue for the UI topic feel free to add your thoughts #3  

```
// Handle the "All" response - 4.x-DEV
  if (msg.json.temperatures != null) {parseTemps(msg.json.temperatures)} else {log.debug("no Temps in msg")}
  if (msg.json.circuits != null){ parseCircuits(msg.json.circuits)} else {log.debug("no Circuits in msg")}
  if (msg.json.pumps != null) {parsePump(msg.json.pumps)} else {log.debug("no Pumps in msg")}
  if (msg.json.valves != null) {parseValve(msg.json.valves)} else {log.debug("no Valve in msg")}
  
  // Handle the "All" response - 4.0.0(?)
  //if (msg.json.temperature != null) {parseTemps(msg.json.temperature)} else {log.debug("no Temps in msg")}
  //if (msg.json.circuit != null){ parseCircuits(msg.json.circuit)} else {log.debug("no Circuits in msg")}
  //if (msg.json.pump != null) {parsePump(msg.json.pump)} else {log.debug("no Pumps in msg")}
  //if (msg.json.valves != null) {parseValve(msg.json.valves)} else {log.debug("no Valve in msg")}
```

**Comment by johnny2678** [comment] 2017-12-01 16:02
Hey guys, sorry for being dense on this.  

Is the working code in the repo or do I need to paste from comments above?  I pulled the latest repo code but I'm still getting a blank Pool Controller device screen (same as my first post).

ST logs don't say anything, other than:
```7a92b045-8e40-4bda-95c6-7933ca013009  10:04:50 AM: info Requested a refresh```
...when I hit the refresh button.

I'm on the latest PoolController from the 4.x-DEV branch:
```
pi@poolpi:~/nodejs-poolController $ git status
On branch 4.x-DEV
Your branch is up-to-date with 'origin/4.x-DEV'.
```

Nothing in the PoolController debug output either that says it's outputting to ST:
```
10:45:34.953 INFO CHECKING DELAY! 0
10:45:54.544 INFO Msg# 96672 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:46:30.145 INFO CHECKING DELAY! 0
10:46:54.545 INFO Msg# 96756 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:47:29.384 INFO CHECKING DELAY! 0
10:47:54.549 INFO Msg# 96837 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:48:30.647 INFO CHECKING DELAY! 0
10:48:54.563 INFO Msg# 96930 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:49:29.878 INFO CHECKING DELAY! 0
10:49:55.038 INFO Msg# 97013 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:49:56.843 INFO CHECKING DELAY! 0
10:50:06.931 INFO CHECKING DELAY! 0
10:50:29.130 INFO CHECKING DELAY! 0
10:50:54.553 INFO Msg# 97100 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:51:18.269 INFO CHECKING DELAY! 0
10:51:30.375 INFO CHECKING DELAY! 0
10:51:54.557 INFO Msg# 97191 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:52:19.502 INFO CHECKING DELAY! 0
10:52:29.596 INFO CHECKING DELAY! 0
10:52:54.752 INFO Msg# 97282 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:53:28.857 INFO CHECKING DELAY! 0
10:53:54.562 INFO Msg# 97382 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:54:30.100 INFO CHECKING DELAY! 0
10:54:50.999 INFO CHECKING DELAY! 0
10:54:54.562 INFO Msg# 97475 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:55:01.191 INFO CHECKING DELAY! 0
10:55:11.190 INFO CHECKING DELAY! 0
10:55:29.366 INFO CHECKING DELAY! 0
10:55:54.567 INFO Msg# 97566 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:56:20.517 INFO CHECKING DELAY! 0
10:56:30.609 INFO CHECKING DELAY! 0
10:56:54.565 INFO Msg# 97662 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:57:31.857 INFO CHECKING DELAY! 0
10:57:54.977 INFO Msg# 97753 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:58:23.025 INFO CHECKING DELAY! 0
10:58:29.084 INFO CHECKING DELAY! 0
10:58:43.215 INFO CHECKING DELAY! 0
10:58:54.955 INFO Msg# 97858 Light group/positions are: 2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10:59:14.201 INFO CHECKING DELAY! 0
```

What am I missing?

**Comment by bsileo** [comment] 2017-12-01 16:10
@johnny2678 Did you install this? https://github.com/bsileo/SmartThings_Pentair/tree/master/nodejs-poolController/src/integrations

**Comment by johnny2678** [comment] 2017-12-01 16:15
@bsileo Yes, it's in there.

and the config.json is updated:
```
    "integrations": {
        "socketISY": 0,
        "outputSocketToConsoleExample": 0,
        "outputToSmartthings": 1
    },
    "outputToSmartthings": {
        "address": "192.168.5.[XXX]",
        "port": "39500"
    },
```

**Comment by johnny2678** [comment] 2017-12-01 16:17
oops, just noticed what @donkarnag mentioned above... File is `outputToSmartThings.js` but integration reference is `outputToSmartthings` (missing capital 'T' in Things)

fixed and restarting...

**Comment by johnny2678** [comment] 2017-12-01 16:19
BINGO... it just came alive.
![image](https://user-images.githubusercontent.com/8219743/33491868-825c933a-d689-11e7-8901-f5ab344d74bc.png)

**Comment by bsileo** [comment] 2017-12-01 16:39
Great news @johnny2678 you live somewhere warm given those temps!

**Comment by johnny2678** [comment] 2017-12-01 18:11
FL, but still need a solar heater and solar blanket to keep temps around 80 ;)

**Closed** 2017-12-02 19:45 UTC
