### ISSUE TITLE
Re-Setup Issues

### ISSUE THREAD

**Issue by donkarnag** [bsileo/SmartThings_Pentair#19] opened 2017-12-28 00:05 UTC
@bsileo I seem to have broken everything updating things.  I updated to the latest nodejs code (which breaks the smartthings integration - the reference to poolController.web.expresstransport no longer exists - I overrode it by adding a protocol variable in the outputToSmartThings section and changed the integration file)
But the settings fields in smartthings was changed too?  It no longer has a port, and Live Logging shows that it is trying to contact the server at `Try for 'sendEthernet' http://null:null/all`.  
Any thoughts?

Also, the Chorinator and Intellichem portions don't install at all - is that part of the uPNP stuff you are putting in place?

**Comment by tagyoureit** [comment] 2017-12-28 18:43
@donkarnag Yes, we updated the settings for the web servers.  
poolController.web.expresstransport should now be `container.settings.get('httpExpressPort')`.  The relevant lines will be [here](https://github.com/tagyoureit/nodejs-poolController/blob/4.x-DEV/src/etc/settings.js#L112).

**Comment by bsileo** [comment] 2017-12-30 20:35
Did you get all the latest code from github @donkarnag ? I made a bunch of environment breaking changes so I recommend you refresh everything including installing the new Smartapp that controls it all. Unfortunately, you will need to delete you current PoolController device and let it be recreated by the SmartApp to fix everything.  I changed the way the main and child devices are identified and this will not work if the devices are not created new.

**Comment by tagyoureit** [comment] 2018-01-06 17:37
Saw this today:

```
2afea3d9-ce51-4ea5-863f-6892c4c27b87  9:34:42 AM: info The Pool Controller Device with dni: 000000000000 already exists...cleanup config
2afea3d9-ce51-4ea5-863f-6892c4c27b87  9:34:42 AM: debug getChildDevices(false), children=1
2afea3d9-ce51-4ea5-863f-6892c4c27b87  9:34:42 AM: debug Updated with settings: [includeChlorinator:true, controllerPort:3000, controllerIP:192.168.1.100, deviceName:Pool, includeIntellichem:false, selectedDevices:[000000000000], includeSolar:true, includeSpa:true]
```

That isn't the right address for my pool controller... not sure why it picked this. up.  Could be something on my end, but clearly the DNI 000000000000 isn't correct.

**Comment by tagyoureit** [comment] 2018-01-06 17:48
Continuing this path,  I setup my controller manually.  Nitpic issue, when the screen refreshes every 1 second, it closes the manual entry part.  Another small item, in the logs I see

```
8839a0d6-91a4-4a73-86bf-0b1e555af39e  6:53:05 PM: debug Updated with settings: [includeSolar:true, deviceName:Pool, controllerIP:192.168.1.100, selectedDevices:[B827EB73BA9B], includeIntellichem:false, includeChlorinator:true, controllerPort:3000, includeSpa:true]
8839a0d6-91a4-4a73-86bf-0b1e555af39e  6:52:53 PM: error java.util.concurrent.TimeoutException: Execution time exceeded 20 app execution seconds: 71656652828024
8839a0d6-91a4-4a73-86bf-0b1e555af39e  6:52:31 PM: info Creating Pool Controller Device with dni: B827EB73BA9B
```

It shows the 192.168.1.100 even though I changed it.  This seems to just be a log issue, however, as the Data on the installed component shows my correct address.

**Comment by bsileo** [comment] 2018-01-09 21:29
I have not seen the all 0's DNI issue reproduce here. Any idea what may have been happening on the lan or hub to cause this?

**Comment by bsileo** [comment] 2018-01-09 21:30
I took the hidden:true out of the Manual config section to help with that. Its an ST problem. You want to refresh somewhat often so that the ones found show up (set to 5 seconds) but this redoes the hiding regardless of the user's actions...In reality there is almost no reason for the manual approach at this point with SSDP built into poolController. Thoughts on just removing that?

**Comment by tagyoureit** [comment] 2018-01-10 04:09
> Any idea what may have been happening on the lan or hub to cause this?
Being that I can't even reset it now... who knows!  We'll just leave this for now and see if it happens again.

> Thoughts on just removing that?
I'd say just leave it in for now.  I know at least one person who installed the poolController app on an AWS server and connects to it via a SSH tunnel.  There may be reasons to manually add the IP if the SSDP won't travel across the tunnel (which I'm not sure).  Maybe it could be on another page that doesn't refresh?

**Comment by bsileo** [comment] 2018-01-10 13:46
Ok good points. I have removed the hidden flag for now. The code already handles auto detected and manually entered options so both can be used.

**Comment by donkarnag** [comment] 2018-01-10 17:52
@bsileo Sorry for disappearing.  The Xmas season had some unexpected surprises that took all of my time.  I am going to try to focus on this a bit again.
I just deleted all of my nodejs and ST code and started again.  I still get an error.  It doesn't seem to know where to send the refresh request.  Also, neither the chlorinator or intellichem children are created on initialization.  A couple of questions..
* What in the nodejs messages / config allows ST to know that there is an intellichem installed?  I have logIntellichem:1
* Where does it get the IP address to ping the nodejs server?  I have the Network ID set to the IP for the nodejs server, but it doesn't seem to be pulling from that.  There are no settings for IP or port any more, so not from there...  I see that it tries to use GetDataValue but I am having trouble tracking that back to where that is set.  Could you help?
* Should the Network ID be the IP, or IP:3000?

Thansk!

1b373464-565d-4ac0-97d6-ac9c4bf24cfe  9:21:15 AM: debug Try for 'sendEthernet' http://null:null/all
1b373464-565d-4ac0-97d6-ac9c4bf24cfe  9:21:15 AM: info Requested a refresh

**Comment by tagyoureit** [comment] 2018-01-10 18:25
> What in the nodejs messages / config allows ST to know that there is an intellichem installed? I have logIntellichem:1

logIntellichem=1 is only for logging in the node app.  In the setup in ST SmartApp, you can use a toggle to enable/disable the intellichem.  Note: the intellichem hasn't fully been tested in the node app because I don't have one installed on my system.   There also will be changes in the node `config.json` to enable/disable the intellichem but it isn't there yet.

> Where does it get the IP address to ping the nodejs server? I have the Network ID set to the IP for the nodejs server, but it doesn't seem to be pulling from that. There are no settings for IP or port any more, so not from there... I see that it tries to use GetDataValue but I am having trouble tracking that back to where that is set. Could you help?

You should update the nodejs-poolController code (4.x-Dev branch).  It includes SSDP for ST to autofind the ST hub.

> Should the Network ID be the IP, or IP:3000?

this is only if you are configuring the IP manually (which you shouldn't need to do if you upgraded to the latest nodejs-poolController app).  But it the IP would be the IP address xxx.xxx.xxx.xxx and the port would be 3000.

**Comment by bsileo** [comment] 2018-01-10 18:28
> What in the nodejs messages / config allows ST to know that there is an intellichem installed? I have logIntellichem:1

To follow this, the automatic configuration of the SmartThings devices based on the poolController is not in place yet, so the user MUST manually adjust the setting in the SmartApp configuration screens for this to work correctly.  Once we get the auto config running, it will set these based on what it detects on the poolController side.

**Comment by donkarnag** [comment] 2018-01-10 18:28
Thanks, I updated the nodejs code earlier today, as well as the newest ST code.  I don't have any experience with SSDC, but atuofind doesn't seem to be working.  Any quick way to debug before I start digging in?

**Comment by tagyoureit** [comment] 2018-01-10 18:29
did you run `npm update` on the nodejs-poolController app?  There are new modules that enable the SSDP config.

**Comment by donkarnag** [comment] 2018-01-10 18:31
@tagyoureit yes, `npm update` complete.  @bsileo  where are the adjustments and the config screen?  There used to be config for IP and port, but no longer - should this be manually coded in the device type?

**Comment by bsileo** [comment] 2018-01-10 18:31
You can use Wireshark to sniff the SSDP packets if you are familiar with that tool.  I think above that level though there should be some logging you can see int he poolCOntroller to indicate SSDP traffic is happening and can also look at the live logging on ST to see the discovery process happening.  here is what I see in Smartthings:
`LogsClear
52b36282-f377-476a-bd80-12b22414d372  1:31:24 PM: info Verified a device - device.value > [model:, ssdpUSN:uuid:806f52f4-1f35-4e33-9299-b827eb3bb77a::urn:schemas-upnp-org:device:PoolController:1, verified:true, name:, networkAddress:C0A802D0, ssdpNTS:null, serialNumber:, devicetype:04, mac:B827EB3BB77A, deviceAddress:0BB8, hub:d15ce14d-4dce-420d-88d4-33bcb3c541d0, ssdpPath:/device, ssdpTerm:urn:schemas-upnp-org:device:PoolController:1, stringCount:04]
52b36282-f377-476a-bd80-12b22414d372  1:31:24 PM: debug DDHandler - > physicalgraph.device.HubResponse(index:15, mac:B827EB3BB77A, ip:C0A802D0, port:0BB8, requestId:e81d4ba7-0a31-4ec9-b378-ea5433faa557, hubId:d15ce14d-4dce-420d-88d4-33bcb3c541d0, callback:deviceDescriptionHandler)
52b36282-f377-476a-bd80-12b22414d372  1:31:24 PM: info Verify UPNP PoolController Device @ http://192.168.2.208:3000/device
52b36282-f377-476a-bd80-12b22414d372  1:31:19 PM: trace discover_devices: subscribe to location urn:schemas-upnp-org:device:PoolController:1`

**Comment by bsileo** [comment] 2018-01-10 18:34
> @tagyoureit yes, npm update complete. @bsileo where are the adjustments and the config screen? There used to be config for IP and port, but no longer - should this be manually coded in the device type?

Did you start from the SmartApp for installation?  This automatically configures the settings on the DeviceHandler and maintains them going forward, such as if the IP address changes on the poolController.

**Comment by donkarnag** [comment] 2018-01-10 18:36
I am not seeing anything like this (really, nothing).  
I installed from the IDE - all the children were created before I opened the iphone app.  Would it make a difference?

**Comment by bsileo** [comment] 2018-01-10 18:37
Yes. You have to start from the SmartApp via the mobile app. That configures all the parameters for the device. I moved it over to the "preferred" approach from SmartThings for LAN connected devices which makes it much closer to software than could be used by many more folks without the heavy lifting under the covers.

**Comment by donkarnag** [comment] 2018-01-10 18:38
OOOOOOOOOH - there is a SmartApp!!!!
I completely missed that!!

**Comment by bsileo** [comment] 2018-01-10 18:41
Now I am excited to hear if it works for you!

**Comment by donkarnag** [comment] 2018-01-10 18:44
Sorry for dragging you through that.  I now have 53 AUX children :).  not updating just yet - but much farther along.  thanks.

**Comment by bsileo** [comment] 2018-01-10 18:44
yeah I just hit that bug looking at it.

**Comment by donkarnag** [comment] 2018-01-10 18:45
It is getting a response back - I am getting notes of which sections have no data, but apparently not getting beyond that...

**Comment by bsileo** [comment] 2018-01-10 18:55
Lame mistake I forgot to cast a string to an int.  I just pushed a fix.
Need this code changed in manageChildren() if you want to patch locally:

`  
def numCircuits = getDataValue("numberCircuits")    
    if (numCircuits == null) { numCircuits = 8 }
    else { numCircuits = numCircuits.toInteger() }
    log.debug "Creating ${numCircuits} for this device"
    for (i in 1..numCircuits) {
`

**Comment by bsileo** [comment] 2018-01-10 19:03
> It is getting a response back - I am getting notes of which sections have no data, but apparently not getting beyond that...

I would expect you will see it getting data back for Temps and Circuits at a minimum. You can fire this by hitting the refresh button and should see that process in your ST logs.

**Comment by donkarnag** [comment] 2018-01-10 19:15
Hmmm - I am getting temperatures back only, and it doesn't seem to be in the same format as I remember a month ago.
I added a `log.debug(msg.json)` and see this:
`[heaterActive:0, spaHeatMode:0, poolHeatMode:0, spaTemp:49, poolHeatModeStr:OFF, freeze:0, poolTemp:49, spaSetPoint:104, poolSetPoint:103, spaHeatModeStr:OFF, airTemp:52, solarTemp:52]`
which doesn't seem to have the key there, so it is not trying to parse it correctly.

**Comment by bsileo** [comment] 2018-01-11 21:50
I think this was resolved via a reinstall of the poolController and ST SmartApp and Devices.  May be other underlying issues but the setup is OK now so closing. Let me know if otherwise @donkarnag

**Closed by bsileo** 2018-01-11 21:50 UTC
